### ISSUE TITLE
GsoC Proposal 2019

### ISSUE THREAD

**Issue by raghav9-97** [FluxML/model-zoo#114]
Hi All!! I am a Gsoc'19 aspirant and have been contributing to JuliaLang and model-zoo for a while.I want to contribute to the Flux during the summer project.I have an idea in my mind which is a kind of three stages of work.

First step would be to create good implementation of some toy RL problems just to know Flux well.Next step is to implement sparsification of neural network algorithm using sensitivity regularization using NIPS Challenge Paper 
http://papers.nips.cc/paper/7644-learning-sparse-neural-networks-via-sensitivity-driven-regularization

This would be tested on some known sparsifiable networks like ImageNet, VGGNet and last step is to experiment it on RL problems.
Also, another idea I had in mind was to port fast.ai courses into Julia which would be a great fun!!

Please provide suggestions as I would like to start working on proposal right away @MikeInnes @ViralBShah @dhairyagandhi96 @staticfloat

**Comment by ToucheSir** [comment]
For anyone coming across this, we don't currently have a GSoC Project for the model zoo. If that changes in the future, the place to check is https://julialang.org/jsoc/gsoc/flux/.
