### ISSUE TITLE
Tutorial: throws an error when calling `m(x)` (output of Dense)

### ISSUE THREAD

**Issue by arnaudmgh** [FluxML/model-zoo#121]
Here: https://github.com/FluxML/model-zoo/blob/7623b854d9792411ff4206d9a33151389dedc444/tutorials/60-minute-blitz.jl#L201

Throws:
`ERROR: MethodError: no method matching make_makeargs(::Base.Broadcast.Broadcasted{Flux.Tracker.TrackedStyle,Nothing,typeof(identity),Tuple{Base.Broadcast.Broadcasted{Flux.Tracker.TrackedStyle,Nothing,typeof(+),Tuple{TrackedArray{…,Array{Float64,1}},TrackedArray{…,Array{Float64,1}}}}}})`

Even when activating the project with `]activate .`

Also, the Flux version in Project.toml starts to be outdated - for instance, I don't think there is a `derivative` function anymore. So I guess one question is, whether it's worth to fix this bug using Flux 0.6.8, or re-writing the tutorial for a more recent version of Flux.

**Comment by aminya** [comment]
I think this was fixed by https://github.com/FluxML/model-zoo/pull/143 .
