### ISSUE TITLE
UndefVarError: derivative not defined

### ISSUE THREAD

**Issue by barcoyou** [FluxML/model-zoo#133]
julia> using Flux.Tracker:derivative
ERROR: UndefVarError: derivative not defined

**Comment by basjacobs93** [comment]
See [this issue](https://github.com/FluxML/model-zoo/issues/118): `derivative` has been replaced by `gradient`.

**Comment by aminya** [comment]
This was fixed by https://github.com/FluxML/model-zoo/pull/143 . This can be closed
