### ISSUE TITLE
Switch from MNIST.jl to MLDatasets.jl?

### ISSUE THREAD

**Issue by amellnik** [FluxML/model-zoo#15]
Would it be OK to swap the data-providing package for the mnist example?  MNIST.jl has deprecation warnings on 0.6 and it seems like MLDatasets is more active.  This would also allow the mnist example to be run with the fashion-MNIST dataset.  

If there's no objections I'll submit a PR.

**Comment by MikeInnes** [comment]
Sounds good in principle. Right now though the package's license-agreement UI is a bit of a deal breaker though, as it expects a terminal to be present. We can wait for Juno's terminal work to be out, or I'm equally happy to fold MNIST.jl into Flux.Data.

**Comment by Evizero** [comment]
the agreement prompt can be suppressed. 

as a side note, the publishing waits for the merge of https://github.com/JuliaML/MLDatasets.jl/pull/12, which waits for a couple small changes to https://github.com/oxinabox/DataDeps.jl

I can make some noise once the package is registered

**Comment by MikeInnes** [comment]
Ok awesome. I think registration would also be useful for us, but let me know once that happens!

**Comment by shivam207** [comment]
I have created a simple MLP model which download data using MLDatasets.jl instead of MNIST.jl. Should I open a PR for it?

**Comment by MikeInnes** [comment]
Right now MNIST is provided directly by Flux ([example](https://github.com/FluxML/model-zoo/blob/9fb7c7d1b1b14b0577f6271f6354b66432b4a87b/mnist/conv.jl)) so the use of MNIST.jl isn't really an issue any more.
