### ISSUE TITLE
sde and dde need names swapped

### ISSUE THREAD

**Issue by ljschumacher** [FluxML/model-zoo#154]
The two examples for SDEs and DDEs have been named the wrong way round. They are linked from here: https://julialang.org/blog/2019/01/fluxdiffeq

so other/diffeq/dde.jl should be called sde.jl and vice versa

**Comment by RobWalt** [comment]
This really needs to be fixed. Especially since it isn't a big issue and causes a lot of confusion. It's gonna take less than 2 minutes ...

**Comment by RobWalt** [comment]
Nevermind. The code is old and not working anymore anyways. For everyone else searching some code examples, I suggest https://diffeqflux.sciml.ai/dev

**Comment by joostveenema** [comment]
These models have been removed and the README already links to the SciML tutorials. Can be closed.
