### ISSUE TITLE
How do you apply the cmu phones model?

### ISSUE THREAD

**Issue by davidavdav** [FluxML/model-zoo#16]
The code in the phonemes example looks amazingly simple.  However, I cannot figure out how to apply the model at test time, i.e., how would a function `predict(model, word)` look like?
```julia
function predict(model, word)
   Xs = tokenise(word, alphabet)
   ## apply the RNN
end

**Comment by MikeInnes** [comment]
Just added this, hopefully it should be pretty clear how to use it!
