### ISSUE TITLE
What is the function make("env_name")?

### ISSUE THREAD

**Issue by adamryczkowski** [FluxML/model-zoo#160]
I find it in e.g. `model-zoo/games/differentiable-programming/cartpole/DQN.jl`
I understand it must be something trivial and non-essential, but I can't find any reference what is it. Would you be so kind and attach a link to the documentation/source of this function somewhere in the docs?

**Comment by tejank10** [comment]
It is defined here[here](https://github.com/FluxML/Gym.jl/blob/6246b0a629335682dbc64249dc52731233be3705/src/Envs/registration.jl#L108). It is just used to create and instantiate environment. Pretty much same as `gym.make(...)` in openai gym

**Comment by dhairyagandhi96** [comment]
Good to close now?

**Comment by dhairyagandhi96** [comment]
Closing since it seems there does not seem to be much activity in this issue. Do feel free to open if something is unclear still
