### ISSUE TITLE
Plotting gives 'Send: No Error' for Lotka-Volterra and Neural_ODE examples

### ISSUE THREAD

**Issue by anandijain** [FluxML/model-zoo#162]
[Lotka Ex](https://github.com/FluxML/model-zoo/blob/master/other/diffeq/lotka-volterra.jl)
[Neural ODE Ex](https://github.com/FluxML/model-zoo/blob/master/other/diffeq/neural_ode.jl)
`julia version 1.1.1`

When running these two examples as is from terminal, I get the printout `Send: No error`, repeated a bunch of times.

I think that it is an error related to plotting.

For the neural ODE example, I get the loss printed, as well as `Send: No error`.

I believe that the code is using default Plots backend:
`Plots.GRBackend()`

Thanks!

**Comment by ChrisRackauckas** [comment]
I think the manifest just needs to be updated on these.
