### ISSUE TITLE
issue with BSON

### ISSUE THREAD

**Issue by frank-ccc** [FluxML/model-zoo#164]
Hi all,
I am writing to report 2 unresolved issues:

1. the following line 
    julia > BSON.@save "mnist_conv.bson" model epoch_idx acc
    gives the following error
    ERROR: LoadError: type Method has no field sparam_syms

2. the maxpool layer is not updated to the latest syntax
    MaxPool((2,2))(x)
    or
    maxpool(x, PoolDims(x,(2,2)))

Thank you,
Frank

**Comment by aminya** [comment]
This should be fixed by https://github.com/MikeInnes/BSON.jl/pull/37 . This can be closed.

**Comment by hossein-pourbozorg** [comment]
maxpool layer is updated in #150
