### ISSUE TITLE
60 minute blitz

### ISSUE THREAD

**Issue by frank-ccc** [FluxML/model-zoo#165]
Dear all,
great package!
In the 60 minutes blitz file, I find at line 22
using Flux.Tracker: derivative
which gives the following error
ERROR: LoadError: UndefVarError: derivative not defined
seems derivative is no longer defined.
Thank you.
Frank

**Comment by aminya** [comment]
I ran into the same thing:
https://github.com/FluxML/model-zoo/issues/166

Run this code to fix the problem:
```julia
using Flux
```
Generally, you don't need to include individual functions one by one! Just include the whole Flux.

**Comment by aminya** [comment]
This is addressed in https://github.com/FluxML/model-zoo/pull/140 or https://github.com/FluxML/model-zoo/pull/143. But there is no one to merge these pull requests.

**Comment by dhairyagandhi96** [comment]
Closed by #143
