### ISSUE TITLE
VAE: mutating arrays is not supported

### ISSUE THREAD

**Issue by nightingale38** [FluxML/model-zoo#190]
When I try to run the vae.jl from the model zoo, I get an error "LoadError: Mutating arrays is not supported". I put the [stacktrace](https://github.com/FluxML/model-zoo/files/4041475/stacktrace.txt) in a file because it is gigantic.

 I also get this error when I try to add a L2 regularisation on a simple autoencoder (which works without the L2 regularisation).  I added this L2 regularisation the same way it is done in vae.jl at line 43:
loss(X) = -L̄(X) + 0.01f0 * sum(x->sum(x.^2), params(f))

PS: I'm using Julia 1.2.0 and Flux 0.10.0.

**Comment by CarloLucibello** [comment]
those issues should be fixed in latest zygote version, feel free to reopen if that's not the case
