### ISSUE TITLE
char-rnn: truncate! not defined

### ISSUE THREAD

**Issue by daob** [FluxML/model-zoo#191]
While running the code in text/char-rnn, I get an error "truncate! not defined". Indeed, truncate! is nowhere to be found in the current (0.10) release of Flux. Should this be reset! ?

**Comment by joostveenema** [comment]
The truncate! call has been removed in https://github.com/FluxML/model-zoo/commit/72f7e34c782b2d437e23a8e6e50687d8075153ba
