### ISSUE TITLE
Contributing to model-zoo

### ISSUE THREAD

**Issue by apprenticearnab** [FluxML/model-zoo#200]
Hi , I am a GSoC 2020 aspirant and looking for contributing to model-zoo of FluxML.I have the idea of implementing Ensemble Neural Networks(ENN)(the optimization process relies on covariance matrices rather than derivatives) and multivariate LSTM-FCN for time series classification to model-zoo. Please tell me if these are feasible or not . I have some experience with NLP , Sequence modelling and Deep learning .

**Comment by logankilpatrick** [comment]
Hey! If you are still interesting in contributing, please ping us on Slack: https://julialang.org/slack/
