### ISSUE TITLE
Update diffeq examples

### ISSUE THREAD

**Issue by sdwfrost** [FluxML/model-zoo#236]
Hi @MikeInnes @ChrisRackauckas 

There's been lots of progress on DifferentialEquations.jl, and the differential equation examples are now broken due to changes in the API. I may well get round to fixing these myself, but in case you get a chance, I'm flagging here.

**Comment by ChrisRackauckas** [comment]
The ones from here should probably just be deleted. The tutorials on this are being maintained at https://diffeqflux.sciml.ai/dev/
