### ISSUE TITLE
Boston example isn't very good (diverging loss)

### ISSUE THREAD

**Issue by ayush-1506** [FluxML/model-zoo#244]
Running the boston example (and logging the loss at each epoch) shows that the loss isn't converging (Final loss at the end of 500 epochs is `loss(x_train, y_train) = 1.8458054620198193e230`).

Ran the model several times, similar result every time.

**Comment by joostveenema** [comment]
Fixed in https://github.com/FluxML/model-zoo/pull/273 (incorrect gradient update)
