### ISSUE TITLE
LoadError in mlp.jl

### ISSUE THREAD

**Issue by tberky** [FluxML/model-zoo#246]
Hello, i am having a lot of errors in most models from model-zoo. For example in mlp.jl i am getting 'LoadError: UndefVarError: flatten not defined' and more. Is it because of versions i am using? Im running Julia 1.4.2 via Juno in Atom and Flux i added just by 'Pkg.add Flux' so i didnt defined version of it. 

Can somebody help?
![2020-07-31_10h16_53](https://user-images.githubusercontent.com/69008406/89015205-f6b4b280-d316-11ea-9ccc-2622b03e441a.png)

**Comment by joostveenema** [comment]
Fixed, same as https://github.com/FluxML/model-zoo/issues/243.
