### ISSUE TITLE
CuArrays Dependency for 60 Minute Blitz

### ISSUE THREAD

**Issue by adinhobl** [FluxML/model-zoo#252]
In [60-minute-blitz.jl](https://github.com/FluxML/model-zoo/blob/master/tutorials/60-minute-blitz.jl), I'm having difficulty getting both CuArrays and Flux to both run their associated lines and it has to do with dependencies. 

```
using CuArrays
x = cu(rand(5, 3))

f(x) = 3x^2 + 2x + 1

f(5)

using Flux: gradient

df(x) = gradient(f, x)[1]

df(5)

ddf(x) = gradient(df, x)[1]

ddf(5)

```

1. add CuArrays then Flux
    [3a865a2d] CuArrays v2.2.2
    [587475ba] Flux v0.8.3
    If I use these I get `ERROR: Use `gradient(...; nest = true)` for nested derivatives` for the `ddf(5)` line

1. add CuArrays then Flux, then `]up Flux`
    [3a865a2d] CuArrays v2.2.2
    [587475ba] Flux v0.10.4
    I get the same error.

1. add Flux only
    [587475ba] Flux v0.11.1
    I don't get that nested gradient error but any attempt to add CuArrays downgrades Flux

Everything in the file seems to work if I replace `using CuArrays` with `using CUDA` and the fresh default packages work out by default so that the gradients no longer say `(tracked)`. I'm not sure if there is any performance or behind-the-scenes difference though. 
  [052768ef] CUDA v1.2.1
  [587475ba] Flux v0.11.1

You could also change the section at lines 276 and 277 to remove `using Zygote` and `using CuArrays`. 

Related discussion #https://github.com/SciML/DiffEqFlux.jl/issues/390

**Comment by DhairyaLGandhi** [comment]
Yeah the environment needs updating, a PR doing that would be well appreciated

**Comment by adinhobl** [comment]
I'll submit one soon with the changes I mentioned above.
