### ISSUE TITLE
CNN MNIST

### ISSUE THREAD

**Issue by tberky** [FluxML/model-zoo#264]
Hello guys,

i am trying to make my own super simple CNN for MNIST based on CNN here in model-zoo. My code is following.

`using Pkg
Pkg.add("Flux")
Pkg.add("Images")
Pkg.add("Plots")
Pkg.add("CUDA")
using Flux, Flux.Data.MNIST, Images, Plots, CUDA

labels = MNIST.labels();
images = MNIST.images();

xs = [Flux.unsqueeze(Float64.(img), 3) for img in images[1:5000]]
ys = [Flux.onehot(label, 0:9) for label in labels[1:5000]]

imgsize = (28,28,1)
model = Chain(Conv((3, 3), imgsize[3]=>16, pad=(1,1), relu),
        MaxPool((2,2)),
        Conv((3, 3), 16=>32, pad=(1,1), relu),
        MaxPool((2,2)),
        Conv((3, 3), 32=>32, pad=(1,1), relu),
        MaxPool((2,2)),
        flatten,
        Dense(288,10, identity),
        softmax)

model = gpu(model)

L(x, y) = Flux.crossentropy(model(x), y)
opt = Descent(0.1)
databatch = (Flux.batch(xs), Flux.batch(ys)) |> gpu
Flux.train!(L, params(model), Iterators.repeated(databatch, 100), opt,
cb = Flux.throttle(() -> println("Probíhá trénování"), 5))

test(i) = findmax(model(Flux.unsqueeze(Float64.(images[i]),4)))[2]-1
sum(test(i) == labels[i] for i in 1:60000)/60000`

and somehow i cannot test it giving me this error
`LoadError: BoundsError: attempt to access (28, 28)
  at index [3]
in expression starting at C:\Users\tomic\OneDrive\Plocha\BP\julia\3_3.jl:40
getindex at tuple.jl:24 [inlined]
getindex at range.jl:304 [inlined]
unsqueeze(::Array{Float64,2}, ::Int64) at utils.jl:208
test(::Int64) at 3_3.jl:39
(::var"#146#147")(::Int64) at none:0
MappingRF at reduce.jl:93 [inlined]
_foldl_impl(::Base.MappingRF{var"#146#147",Base.BottomRF{typeof(Base.add_sum)}}, ::Base._InitialValue, ::UnitRange{Int64}) at reduce.jl:58
foldl_impl at reduce.jl:48 [inlined]
mapfoldl_impl at reduce.jl:44 [inlined]
#mapfoldl#204 at reduce.jl:160 [inlined]
mapfoldl at reduce.jl:160 [inlined]
#mapreduce#208 at reduce.jl:287 [inlined]
mapreduce at reduce.jl:287 [inlined]
sum at reduce.jl:494 [inlined]
sum(::Base.Generator{UnitRange{Int64},var"#146#147"}) at reduce.jl:511
top-level scope at 3_3.jl:40
include_string(::Function, ::Module, ::String, ::String) at loading.jl:1088`

**Comment by CarloLucibello** [comment]
please use markdown's code fencing for readability. Also, the correct place for such questions is julia's discouse
