### ISSUE TITLE
GSoC Proposal

### ISSUE THREAD

**Issue by tejank10** [FluxML/model-zoo#28]
I am interested in contributing to the model zoo of FluxML as part of GSoC'18. Below are the models which I want to implement over the course of summer:

- AlphaGo
- Dueling DQN
- Actor-Critic Model
- Asynchronous Actor-Critic Model
- Artistic Style Transfer
- DCGAN
- Spatial Transformer Networks
- [Synthetic Gradients](https://arxiv.org/pdf/1608.05343.pdf)
- [Self Normalizing Neural Networks](http://papers.nips.cc/paper/6698-self-normalizing-neural-networks.pdf)

@MikeInnes Does it sound like a good project to work on?

**Comment by MikeInnes** [comment]
Sounds good – nice and ambitious :)

One thing that would be really interesting is applying AlphaGo or other RL to other games, e.g. chess, pong or tetris. We could possible then get a fun play-against-the-AI demo going via FluxJS.

**Comment by tejank10** [comment]
Thanks :). Playing games against AI made using Flux should be really fun!
I was wondering how should I go about prioritizing the models mentioned above? If we want to deploy the human vs AI game using FluxJS, perhaps I shall give more priority to the RL models.

**Comment by MikeInnes** [comment]
Yeah, let's lean towards the RL stuff for now, and we can branch out if it makes sense.

Worth checking out [Chess.jl](https://github.com/abahm/Chess.jl), haven't looked at it closely but it might be useful as a starting point. Or it should be pretty simple to build a pong simulator or similar.

**Comment by tejank10** [comment]
Thanks for Chess.jl! I'll add the pong simulator as a stretch goal. Perhaps it could be incorporated into Reinforce.jl environment. 
I wanted to know if explaining the architectures I wish to implement in the implementation part of the project proposal would do?

**Comment by tejank10** [comment]
Here is the initial draft of my proposal: [GSoC Proposal](https://docs.google.com/document/d/1nUS_Q11vmhNNjDSBuohXZN9BDddzj9xncd3D_y38ZrY/edit?usp=sharing). I would be grateful if you could provide your valuable inputs over it. Thanks! Looking forward to your comments. :)

**Comment by MikeInnes** [comment]
GSoC is in progress now, so closing these issues.

**Comment by xysun** [comment]
Is there any further update regarding this? I noticed in README it mentioned RL algorithms but couldn't find them.

**Comment by tejank10** [comment]
The RL algorithms mentioned are made as a separate repo, https://github.com/tejank10/Flux-baselines
