### ISSUE TITLE
[GSoC 2021 Proposal] Tutorials for all major models with latest Julia code

### ISSUE THREAD

**Issue by rakesh4real** [FluxML/model-zoo#290]
Hi,

I want to contribute for **tutorials** for major models listed below.

> Please note: the list merely show what I am willing to implement but please feel free to make any changes!

- GoogLeNet
- ResNet
- UNet
- Q-Learning

**Comment by DhairyaLGandhi** [comment]
Ou might want to check out Metalhead.jl, UNet.jl, ReinforcementLearning. What kinds of tutorials were you thinking of?
