### ISSUE TITLE
[GSoC 2021 Proposal] One Shot Learning

### ISSUE THREAD

**Issue by rakesh4real** [FluxML/model-zoo#291]
Hi,

I want to implement the following one-shot learning techniques for GSoC 2021.
Please let me know if these are required

- Siamese networks with contrastive and triplet loss functions
- Protoype network
- Matching network

**Comment by CarloLucibello** [comment]
Hi, 
having all those networks in some repo is surely good. The model-zoo is not the right repo though, since we keep here only a few simple curated examples. Make sure to join the ml-ecosystem-coordination channel on Zulip.

**Comment by DhairyaLGandhi** [comment]
We also can have a repo similar to Metalhead.jl where such model implementations live.

**Comment by darsnack** [comment]
> Make sure to join the ml-ecosystem-coordination channel on Zulip.

Link to stream: https://julialang.zulipchat.com/#narrow/stream/237432-ml-ecosystem-coordination

**Comment by rakesh4real** [comment]
> > Make sure to join the ml-ecosystem-coordination channel on Zulip.
> 
> Link to stream: https://julialang.zulipchat.com/#narrow/stream/237432-ml-ecosystem-coordination

Thankyou! I will continue there.
