### ISSUE TITLE
Can't differentiate foreign call expression with Flux

### ISSUE THREAD

**Issue by tzr7mm** [FluxML/model-zoo#294]
Trying a very simple (toy) problem for PINN and getting this error "Can't differentiate foreign call expression" - can't figure out why. Any help will be greatly appreciated. Thanks in advance

using Flux

NNODE = Chain(x -> [x], # Take in a scalar and transform it into an array
           Dense(1,32,tanh),
           Dense(32,1),
           first) # Take first value, i.e. return a scalar
NNODE(1.0)

g = t -> t*NNODE(t) + 1f0
using Statistics
ϵ = sqrt(eps(Float32))
g_grad = t -> gradient(g,t)

#loss() = mean(abs2(((g(t+ϵ)-g(t))/ϵ) - cos(2π*t)) for t in 0:1f-2:1f0)
loss() = mean(abs2((g_grad(t)[1] - cos(2π*t))) for t in 0:1f-2:1f0)

opt = Flux.Descent(0.01)
data = Iterators.repeated((), 5000)
iter = 0
cb = function () #callback function to observe training
  global iter += 1
  if iter % 500 == 0
    display(loss())
  end
end
display(loss())
Flux.train!(loss, Flux.params(NNODE), data, opt) - _**This where I get the error even though loss() function works fine**_

using Plots
t = 0:0.001:1.0
plot(t,g.(t),label="NN")
plot!(t,1.0 .+ sin.(2π.*t)/2π, label = "True Solution")

**Comment by CarloLucibello** [comment]
beside the fact that you should format your post using code fences (i.e. ```julia) for readability, this is not the right place for such questions. You should try posting on julia's discourse https://discourse.julialang.org/
