### ISSUE TITLE
README: "script.jl" does not exist

### ISSUE THREAD

**Issue by rgobbel** [FluxML/model-zoo#297]
The instructions in the top-level README file for the model-zoo project fail very early: the "script.jl" file mentioned doesn't exist. I understand that there are quite a few other issues at present, but this one seems simple. Not knowing what's intended here, I'll leave this to someone with more knowledge of the package's context and roadmap, if there is one, to fix.

**Comment by DhairyaLGandhi** [comment]
Added a simple blurb to not be so confusing. Thanks!
