### ISSUE TITLE
GSOC Proposal : Computer Vision Networks

### ISSUE THREAD

**Issue by avik-pal** [FluxML/model-zoo#30]
I wish to implement the following network architectures for my GSOC. They are listed in the order of implementation
- [x] VGG16
- [x] VGG19
- [x] ResNet50
- [x] Xception
- [x] Inception V3
- [x] Inception ResNet V2
- [x] MobileNet
- [x] DenseNet
- [ ] NASNet
- [ ] R-FCN
- [ ] Fast R-CNN
- [ ] Faster R-CNN
- [ ] RetinaNet
- [ ] Mask R-CNN (*)

@MikeInnes how does this sound? I wish to test these implementation on the tiny-imagenet-200 dataset or the CIFAR-10

**Comment by MikeInnes** [comment]
GSoC is in progress now, so closing these issues.

**Comment by EMCP** [comment]
anyway I can help with the Faster R-CNN ?  Is someone already working on this?

I am wanting to use transfer learning with Flux, and ween off PyTorch.. but it's tough without a step by step way.. so thinking maybe I can help someone else who may already be in progress?

**Comment by MikeInnes** [comment]
@avik-pal may be able to help or point you to someone working on this, but you might also be interested in signing up to the Julia slack for this kind of thing.

**Comment by avik-pal** [comment]
@dhairyagandhi96 has an implementation of MaskRCNN which is essentially just an extension of Faster RCNN.
