### ISSUE TITLE
Latest versions of DiffEqFlux examples?

### ISSUE THREAD

**Issue by JulesArcher** [FluxML/model-zoo#300]
Hi,

Hi have been trying to run the simple DiffEqFlux examples documented in the user manual without success. There are several instances where the code does not execute 'as is'. Here's a simple example:

ode_data = Array(solve(prob,Tsit5(),saveat=t)) pushes a long error starting with:

**MethodError: Cannot `convert` an object of type DiffEqBase.ODESolution{Float32, 2, Vector{Vector{Float32}}, Nothing, Nothing, Vector{Float32},**

Can anyone point me to versions of examples that are known to work 'out of the box' using the the latest 1.6.1 version of Julia, Flux,...

Thanks!

**Comment by DhairyaLGandhi** [comment]
Could you open an issue on Flux with the examples you're running and the stacktrace? That would be appreciated!

**Comment by JulesArcher** [comment]
It looks like a dependency prevented the most most recent version of Flux. Once upgraded, the first example I tried seems to be working now! Sorry for the 'false alarm'...
