### ISSUE TITLE
No weight initialization in DCGAN

### ISSUE THREAD

**Issue by rutvij-25** [FluxML/model-zoo#309]
I guess the weights should be initialized for the models sampled from a normal distribution with mean = 0 and std = 0.02

**Comment by DhairyaLGandhi** [comment]
Is that initialisation in the paper? Conv layers have an `init` keyword and one can pass in a `Normal` sampling function from Distributions.jl

**Comment by rutvij-25** [comment]
Thanks for the reply, yes it is given in the paper, so ill make the required changes and initiate a PR after testing the model?

**Comment by rutvij-25** [comment]
Yes it's given in the paper

**Comment by CarloLucibello** [comment]
While it is true that the [original paper]( https://arxiv.org/pdf/1511.06434.pdf)
uses N(0, 0.02) init, I think modern standard initialization techniques, implemented in Flux layers' constructors, are what is used in current practice. 
Anyways, is nice to have an example in model-zoo showing non-standard initialization. 

Closed in #311
