### ISSUE TITLE
GSoC Proposal 2018

### ISSUE THREAD

**Issue by ashishpriyadarshiCIC** [FluxML/model-zoo#31]
I am interested in contributing to the model zoo as part of GSoC . Below are the models which I want to implement over the course of summer:

1.KNN
2.Apriori
3.Naive Bayes Classification
4.Association Rules
5.Q-Learning
6.K-means
7.Deep Q Network 
8.Genetic algorithm

@MikeInnes  Is this project good enough for GSoC Sir?

**Comment by MikeInnes** [comment]
GSoC is in progress now, so closing these issues.
