### ISSUE TITLE
conv_mnist pretrained model

### ISSUE THREAD

**Issue by extremety1989** [FluxML/model-zoo#314]
I loaded mnist test data from Kaggle, i wanted to test my pretrained model from conv_mnist, how to use pretrained model to predict image ?

img = test[1011,:] |> Array
img = vec(img)
img = img/255
img = reshape(img,28,28)
img = transpose(img)
Gray.(img)// image of 2

@load "runs/mnist.bson" model
y_pred = model(img)
r = findmax(y_pred) .- (0,1)
r[2]
error : DimensionMismatch("Rank of x and w must match! (2 vs. 4)")

**Comment by DhairyaLGandhi** [comment]
It's hard to know what is happening in the code without a stacktrace. I would say that you need to do a `channelview` on the image and get it into the format Flux expects (`WHCN`).

**Comment by DhairyaLGandhi** [comment]
We can prolly close this for now since it's not strictly an issue, but a question. You might want to check out the JuliaLang Slack or discourse for such questions. Feel free to reopen if you think there's something else that needs to be addressed :)

**Comment by extremety1989** [comment]
@DhairyaLGandhi aa okey,thanks
