### ISSUE TITLE
Flattened data vs Flux.flatten layer in MNIST MLP in the model zoo

### ISSUE THREAD

**Issue by congUoM** [FluxML/model-zoo#316]
Using this example: 
[https://github.com/FluxML/model-zoo/blob/master/vision/mlp_mnist/mlp_mnist.jl](https://github.com/FluxML/model-zoo/blob/master/vision/mlp_mnist/mlp_mnist.jl)

I remove lines 18-19:
`xtrain = Flux.flatten(xtrain)`
`xtest = Flux.flatten(xtest)`

and add the Flux.flatten layer into the model, i.e. changing lines 32-34 into
`return Chain(`
`              Flux.flatten,`
`              Dense(prod(imgsize), 32, relu),`
`              Dense(32, nclasses))`

then the training results (at epoch 10) look like this
`Epoch=10`
`  train_loss = 1.912397, train_accuracy = 8.580243161094225`
`  test_loss = 1.9072858, test_accuracy = 8.375892857142857`
where the size of x at line 85, before fed to the model, is (28, 28, 256)

The (original) correct training results look like this
`Epoch=10`
`  train_loss = 0.19840966, train_accuracy = 0.94455`
`  test_loss = 0.19940367, test_accuracy = 0.9422`
where the size of x at line 85, before fed to the model, is (784, 256).

**Comment by CarloLucibello** [comment]
Hi,
`flatten` is acting properly, you should change the line counting the total number of examples  in the `loss_and_accuracy` from `num +=  size(x, 2)` to `num +=  size(x)[end]`
