### ISSUE TITLE
GSoC Proposal

### ISSUE THREAD

**Issue by prakharcode** [FluxML/model-zoo#32]
I want to participate in GSoC and make a contribution in Flux.jl model zoo and implement the following algorithms 
- RBMs
- Siamese nets
- SARSA(λ)
- TD(λ)
- An implementation of a sequence to sequence network
- Pixel rnn
- Attention network for generating captions
- GRUs
- An easy to call in implementation of all the learning updates
- VAE
- DCGANs
- DenseNet 

And apart from model implementations, I would like to propose a tutorial repo under Flux.jl in which each implementation will be explained in a Jupyter notebook.

@MikeInnes is it a good enough project for GSoC? I would be glad to hear any reviews from you!

**Comment by MikeInnes** [comment]
GSoC is in progress now, so closing these issues.
