### ISSUE TITLE
Minor error in the 60 minute blitz tutorial

### ISSUE THREAD

**Issue by rossinerbe** [FluxML/model-zoo#327]
Hey, just an FYI that the "Deep Learning with Flux - A 60 Minute Blitz" tutorial has a minor error.

When the test data is being prepped for the convolutional net the code used is this:

```
test_x, test_y = CIFAR10.testdata(Float32)
test_labels = onehotbatch(test_y, 0:9)

test = gpu.([(test_x[:,:,:,i], labels[:,i]) for i in partition(1:10000, 1000)])
```

in the third line the `labels` should be `test_labels` otherwise the labels are from the training rather than the test data, which naturally gives pretty random accuracy results later on.

**Comment by ToucheSir** [comment]
Good catch, mind filing a PR?

**Comment by rossinerbe** [comment]
Ah, actually it looks like the error is just in the html of the tutorial at https://fluxml.ai/tutorials/2020/09/15/deep-learning-flux.html, the .jl file in the repository is fine.

**Comment by ToucheSir** [comment]
Yes, that's because the file in this repo is out of date and hasn't been updated to match https://github.com/FluxML/fluxml.github.io/pull/118. So it'd be a 2-step process: typo fix there, and full update here.

**Comment by rossinerbe** [comment]
#328 Gotcha, submitted the PR.
