### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by BoBernhardsson** [FluxML/model-zoo#333]
There is a broken link in this text

The zoo comes with its own [Julia project](https://julialang.github.io/Pkg.jl/latest/#Using-someone-else's-project-1), which lists the packages you need to run the models. You can run the models by opening Julia in the project folder and running

Suggest to change to this link
https://pkgdocs.julialang.org/v1/environments/#Using-someone-else's-project

**Comment by ToucheSir** [comment]
Thabks, do you mind filling a PR?
