### ISSUE TITLE
[Question] how to understand out_conv_size in LeNet5 ?

### ISSUE THREAD

**Issue by nesteiner** [FluxML/model-zoo#368]
here is the code
```julia
function LeNet5(; imgsize=(28,28,1), nclasses=10) 
    out_conv_size = (imgsize[1]÷4 - 3, imgsize[2]÷4 - 3, 16)
    
    return Chain(
            Conv((5, 5), imgsize[end]=>6, relu),
            MaxPool((2, 2)),
            Conv((5, 5), 6=>16, relu),
            MaxPool((2, 2)),
            flatten,
            Dense(prod(out_conv_size), 120, relu), 
            Dense(120, 84, relu), 
            Dense(84, nclasses)
          )
end
```
1. I don't understand why the `out_conv_size` is such value,
2. how do you compute the `out_conv_size` ? 
3. or can you give me an example using `Flux.outputsize` to calculate `out_conv_size` ?
ps: actually I have ask a similar question in slack, but little people reply, so I think how about open a issue, sorry to bother you guys :slightly_smiling_face:

**Comment by ToucheSir** [comment]
Closing as answered on Slack. Most of the Flux contributors live in a much later time zone, so please give us at least 24-48 hours to get around to your question (this is a rule of thumb, _not_ a guarantee). I see it was answered nicely by someone else in a couple hours anyhow, so this can be considered resolved.
