### ISSUE TITLE
julia 1.0.0 support?

### ISSUE THREAD

**Issue by zhangpiu** [FluxML/model-zoo#53]
Print errors when using Metalhead:
WARNING: eval from module Broadcast to Metalhead:    
Expr(:block, #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):388 =#, Expr(:function, Expr(:where, Expr(:call, :flatten, Expr(:::, :bc, Expr(:curly, :Broadcasted, :Style))), :Style), Expr(:block, #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):389 =#, Expr(:&&, Expr(:call, :isflat, :bc), Expr(:return, :bc)), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):390 =#, :args = Expr(:call, :cat_nested, :bc), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):391 =#, Expr(:let, Expr(:block, :makeargs = Expr(:call, :make_makeargs, :bc), :f = Expr(:., :bc, :(:f))), Expr(:block, #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):392 =#, :newf = Expr(:macrocall, Symbol("@inline"), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):392 =#, Expr(:function, Expr(:where, Expr(:tuple, Expr(:::, :args, Expr(:curly, :Vararg, :Any, :N))), :N), Expr(:block, #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):393 =#, Expr(:call, :f, Expr(:..., Expr(:call, :makeargs, Expr(:..., :args))))))), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):395 =#, Expr(:return, Expr(:call, Expr(:curly, :Broadcasted, :Style), :newf, :args, Expr(:., :bc, :(:axes)))))))), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):398 =#, Expr(:macrocall, Symbol("@inline"), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):398 =#, Expr(:function, Expr(:call, :make_makeargs, :makeargs, Expr(:::, :t, Expr(:curly, :Tuple, Expr(:<:, :Broadcasted), Expr(:curly, :Vararg, :Any)))), Expr(:block, #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):399 =#, :bc = Expr(:ref, :t, 1), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):400 =#, Expr(:let, Expr(:block, :makeargs = Expr(:call, :make_makeargs, :makeargs, Expr(:call, :tail, :t)), :f = Expr(:., :bc, :(:f))), Expr(:block, #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):401 =#, Expr(:let, :makeargs = Expr(:call, :make_makeargs, :makeargs, Expr(:., :bc, :(:args))), Expr(:block, #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):402 =#, Expr(:tuple, :headargs, :tailargs) = Expr(:tuple, Expr(:call, :make_headargs, Expr(:., :bc, :(:args))), Expr(:call, :make_tailargs, Expr(:., :bc, :(:args)))), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):403 =#, Expr(:return, Expr(:macrocall, Symbol("@inline"), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):403 =#, Expr(:function, Expr(:where, Expr(:tuple, Expr(:::, :args, Expr(:curly, :Vararg, :Any, :N))), :N), Expr(:block, #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):404 =#, :args1 = Expr(:call, :makeargs, Expr(:..., :args)), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):405 =#, Expr(:tuple, :a, :b) = Expr(:tuple, Expr(:call, :headargs, Expr(:..., :args1)), Expr(:call, :tailargs, Expr(:..., :args1))), #= Symbol("/home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl"):406 =#, Expr(:tuple, Expr(:call, :f, Expr(:..., :a)), Expr(:..., :b))))))))))))))
  ** incremental compilation may be broken for this module **

WARNING: Method definition flatten(Base.Broadcast.Broadcasted{Style, Axes, F, Args} where Args<:Tuple where F where Axes) where {Style} in module Broadcast at broadcast.jl:296 overwritten at /home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl:389.
WARNING: Method definition make_makeargs(Any, Tuple{#s12, Vararg{Any, N} where N} where #s12<:(Base.Broadcast.Broadcasted{Style, Axes, F, Args} where Args<:Tuple where F where Axes where Style<:Union{Nothing, Base.Broadcast.BroadcastStyle})) in module Broadcast at broadcast.jl:334 overwritten at /home/qingzhi/.julia/packages/Flux/kJVo6/src/tracker/array.jl:399.
ERROR: LoadError: UndefVarError: Void not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:319 [inlined]
 [7] eval(::Expr) at ./client.jl:389
 [8] top-level scope at ./none:3
in expression starting at /home/qingzhi/.julia/packages/BSON/VAvDJ/src/BSON.jl:7
ERROR: LoadError: Failed to precompile BSON [fbb218c0-5317-5bc6-957e-2ee96dd4b1f0] to /home/qingzhi/.julia/compiled/v1.0/BSON/3tVCZ.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/qingzhi/.julia/packages/Metalhead/8ZFyX/src/Metalhead.jl:4
ERROR: Failed to precompile Metalhead [dbeba491-748d-5e0e-a39e-b530a07fa0cc] to /home/qingzhi/.julia/compiled/v1.0/Metalhead/OYscp.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834

**Comment by MikeInnes** [comment]
I have some progress on [this branch](https://github.com/FluxML/model-zoo/tree/julia-0.7); just the models with project files for now. We also need updates to Metalhead over at https://github.com/FluxML/Metalhead.jl/pull/19.
