### ISSUE TITLE
Run model zoo on CLArrays?

### ISSUE THREAD

**Issue by DilumAluthge** [FluxML/model-zoo#58]
Per https://github.com/FluxML/model-zoo/issues/20#issuecomment-421446052, most of the models now have support for CuArrays.

Would it be possible to add support for CLArrays as well?

**Comment by MikeInnes** [comment]
This really just depends on https://github.com/FluxML/Flux.jl/issues/173. For some simple things, it should already work, but just needs integration with `gpu` to make it convenient.

**Comment by ToucheSir** [comment]
CLArrays is dead as a dodo now and unlikely to be revived any time soon, we can reopen if that day comes.
