### ISSUE TITLE
char-rnn is missing sampling code

### ISSUE THREAD

**Issue by jpfairbanks** [FluxML/model-zoo#6]
The char-rnn model lost the sampling code when migrating from Flux.jl examples directory to the model-zoo.

https://fluxml.github.io/Flux.jl/release-0.2/examples/char-rnn.html
```julia
function sample(model, n, temp = 1)
  s = [rand(alphabet)]
  m = unroll1(model)
  for i = 1:n-1
    push!(s, wsample(alphabet, softmax(m(unsqueeze(onehot(s[end], alphabet)))./temp)[1,:]))
  end
  return string(s...)
end

sample(model[1:end-1], 100)
```

**Comment by MikeInnes** [comment]
Put this back in the commit above, hope that works for you!
