### ISSUE TITLE
spell out acronyms on REAMDE.md

### ISSUE THREAD

**Issue by johnfgibson** [FluxML/model-zoo#60]
A friendly suggestion: Could you spell out the acronyms in the README.md? Like "RNN (Recurrent Neural Net)" or vice versa?

This would make the page much more comprehensible to people who are not already steeped in machine learning.

**Comment by MikeInnes** [comment]
I'd be happy to add some clarification; feel free to make a PR.

**Comment by vincentzhang** [comment]
Looks like this issue can be closed.
