### ISSUE TITLE
kl-divergence formula in vae seems wrong

### ISSUE THREAD

**Issue by chengchingwen** [FluxML/model-zoo#73]
The kl-divergence for normal distribution should be 
<a href="https://www.codecogs.com/eqnedit.php?latex=KL(N(\mu_1,&space;\sigma_1),&space;N(\mu_2,&space;\sigma_2))&space;=&space;log\frac{\sigma_2}{\sigma_1}&space;&plus;&space;\frac{\sigma_1^2&space;&plus;&space;(\mu_1&space;-&space;\mu_2)^2}{2&space;\sigma_2^2}&space;-&space;1/2&space;\\&space;\text{so,}&space;\\&space;KL(N(\mu_1,&space;\sigma_1),&space;N(0,&space;1))&space;=&space;-log\sigma_1&space;&plus;&space;\frac{\sigma_1^2&space;&plus;&space;\mu_1^2}{2}&space;-&space;1/2&space;\\&space;=&space;\frac{1}{2}(\sigma_1^2&space;&plus;&space;\mu_1^2&space;-1&space;-&space;2log\sigma_1)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?KL(N(\mu_1,&space;\sigma_1),&space;N(\mu_2,&space;\sigma_2))&space;=&space;log\frac{\sigma_2}{\sigma_1}&space;&plus;&space;\frac{\sigma_1^2&space;&plus;&space;(\mu_1&space;-&space;\mu_2)^2}{2&space;\sigma_2^2}&space;-&space;1/2&space;\\&space;\text{so,}&space;\\&space;KL(N(\mu_1,&space;\sigma_1),&space;N(0,&space;1))&space;=&space;-log\sigma_1&space;&plus;&space;\frac{\sigma_1^2&space;&plus;&space;\mu_1^2}{2}&space;-&space;1/2&space;\\&space;=&space;\frac{1}{2}(\sigma_1^2&space;&plus;&space;\mu_1^2&space;-1&space;-&space;2log\sigma_1)" title="KL(N(\mu_1, \sigma_1), N(\mu_2, \sigma_2)) = log\frac{\sigma_2}{\sigma_1} + \frac{\sigma_1^2 + (\mu_1 - \mu_2)^2}{2 \sigma_2^2} - 1/2 \\ \text{so,} \\ KL(N(\mu_1, \sigma_1), N(0, 1)) = -log\sigma_1 + \frac{\sigma_1^2 + \mu_1^2}{2} - 1/2 \\ = \frac{1}{2}(\sigma_1^2 + \mu_1^2 -1 - 2log\sigma_1)" /></a>

but the formula in vae is  
https://github.com/FluxML/model-zoo/blob/a243e8b192236c30064fcdb7a36f17f3b6823c34/vision/mnist/vae.jl#L33

it should be 
```julia
kl_q_p(μ, logσ) = 0.5 * sum(exp.(2 .* logσ) + μ.^2 .- 1 .- 2 .* logσ) 
```
for the last term change from `(logσ)^2` to `2logσ`

**Comment by AbinavRavi** [comment]
Can I take up this issue?

**Comment by chengchingwen** [comment]
@AbinavRavi  sure? I guess it should be easy to fix since it just looks like a typo. However, I'm not the guy who knows divergence very much. Most of the formula were found on the Internet, so maybe we need a double check on the equations.

**Comment by MikeInnes** [comment]
Best to talk to @willtebbutt who wrote this.

**Comment by willtebbutt** [comment]
@chengchingwen you're totally correct. The last term in my implementation is completely off. Not completely sure how this slipped through, but many thanks for finding it. @AbinavRavi I propose that you accept the proposed fix.

**Comment by chengchingwen** [comment]
@willtebbutt I was learning about vae and just stuck on that function for a few days. The interesting part is that even there are some weird term in the code, the model still works well. I guess that's the reason why nobody notice it before.  @AbinavRavi you might also make a pr ?
